spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: auth-service-route
              uri: lb://auth-service
              predicates:
                - Host=auth.api.t1.internship.10.10.146.230.nip.io:8010
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Host=user.api.t1.internship.10.10.146.230.nip.io:8010
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin
                - name: JwtUserEmailheaderFilter
            - id: order-service-route
              uri: lb://order-service
              predicates:
                - Host=order.api.t1.internship.10.10.146.230.nip.io:8010
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin
                - name: JwtUserEmailheaderFilter
            - id: places-service-route
              uri: lb://places-service
              predicates:
                - Host=places.api.t1.internship.10.10.146.230.nip.io:8010
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin
                - name: JwtUserEmailheaderFilter
            - id: visualization-service-route
              uri: lb://visualization-service
              predicates:
                - Host=visualization.api.t1.internship.10.10.146.230.nip.io:8010
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin
                - name: JwtUserEmailheaderFilter
          httpclient:
            connect-timeout: 1000
            response-timeout: 5s
            pool:
              max-idle-time: 5s
          metrics:
            enabled: true

server:
  port: 8010
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
    register-with-eureka: false
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics
    jmx:
      exposure:
        include: '*'
app:
  security:
    jwt:
      jwkSetUri: http://auth-service:8006/.well-known/jwks.json
      publicUrls:
        - "/v3/api-docs/**"
        - "/actuator/**"
        - "/swagger-ui/**"
        - "/swagger-ui.html"
        - "/swagger-resources/**"
        - "/webjars/**"
        - "/favicon.ico"
        - "/error"
        - "/api/v1/auth/**"
