server:
  port: 8006
spring:
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://10.10.146.230:5432/places?schema=account_schema
    username: auth_repo
    password: auth-repo
  kafka:
    bootstrap-servers: 10.10.146.230:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    hostname: localhost
    appname: auth-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8002/eureka/
    healthcheck:
      enabled: true
jwt:
  expiration:
    access: 600000
    refresh: 3600000
logging:
  level:
    org.springframework.security: DEBUG
flyway:
  locations: classpath:db/migration
  schemas: account_schema
  baseline-on-migrate: true