spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/places?schema=places_schema
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        default_schema: places_schema
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false
eureka:
client:
  service-url:
    defaultZone: http://host.docker.internal:8761/eureka/
  register-with-eureka: true
  fetch-registry: true
flyway:
  locations: classpath:db/migration
  schemas: places_schema
  baseline-on-migrate: true
