spring:
  datasource:
    url: jdbc:postgresql://10.10.146.230:5432/places_repo
    username: places_repo
    password: places-repo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        default_schema: places_schema
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: host.docker.internal
    port: 6379
    password: foobared
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

flyway:
  locations: classpath:db/migration
  schemas: places_schema
  baseline-on-migrate: true

