spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/places?schema=${DB_SCHEMA:places_schema}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:user}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:places_schema}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:host.docker.internal}:${EUREKA_PORT:8761}/eureka/
    register-with-eureka: true
    fetch-registry: true

flyway:
  locations: classpath:db/migration
  schemas: ${DB_SCHEMA:places_schema}
  baseline-on-migrate: true

