eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    hostname: user-service
    appname: user-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    healthcheck:
      enabled: true
server:
  port: 8003

spring:
  flyway:
    locations: classpath:db/migration
    schemas: profile_schema
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        default_schema: profile_schema
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://10.10.146.230:5432/profiles?schema=profile_schema
    username: user_repo
    password: user-repo
  kafka:
    bootstrap-servers: 10.10.146.230:9092
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: t1internship.shared.dto
