spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://10.10.146.230:5432/places?schema=visualization_schema
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        default_schema: visualization_schema
    database-platform: org.hibernate.dialect.PostgreSQLDialect
flyway:
  locations: classpath:db/migration
  schemas: visualization_schema
  baseline-on-migrate: true
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    hostname: visualization-service
    appname: visualization-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    healthcheck:
      enabled: true
minio:
  url: http://10.10.146.230:9000
  access-key: minio_root
  secret-key: minio_root_pass
  bucket: bob
server:
  port: 8020
